import type { ArgentinaProvince } from './argentina-provinces';

/**
 * Client-side city suggestions per Argentine province.
 * Used only for UX hints — the user can still type any city freely.
 */
export const AR_TOP_CITIES: Partial<Record<ArgentinaProvince, string[]>> = {
  'Buenos Aires': [
    'La Plata',
    'Mar del Plata',
    'Quilmes',
    'Bahía Blanca',
    'Lomas de Zamora',
    'Lanús',
    'Morón',
    'San Isidro',
    'Tigre',
    'Pilar',
    'Vicente López',
    'Luján',
  ],
  'Ciudad Autónoma de Buenos Aires': [
    'Palermo',
    'Belgrano',
    'Recoleta',
    'Caballito',
    'Villa Devoto',
    'Núñez',
    'San Telmo',
    'Flores',
    'Almagro',
    'Villa Crespo',
  ],
  'Córdoba': [
    'Córdoba',
    'Villa Carlos Paz',
    'Alta Gracia',
    'Río Cuarto',
    'Villa María',
    'Bell Ville',
    'Cosquín',
    'Cruz del Eje',
  ],
  'Santa Fe': [
    'Rosario',
    'Santa Fe',
    'Rafaela',
    'Venado Tuerto',
    'Reconquista',
    'Santo Tomé',
    'Esperanza',
    'San Lorenzo',
  ],
  'Mendoza': [
    'Mendoza',
    'Godoy Cruz',
    'Luján de Cuyo',
    'San Rafael',
    'Maipú',
    'Las Heras',
    'Rivadavia',
  ],
  'Tucumán': [
    'San Miguel de Tucumán',
    'Tafí Viejo',
    'Banda del Río Salí',
    'Yerba Buena',
    'Concepción',
    'Aguilares',
  ],
  'Salta': [
    'Salta',
    'San Ramón de la Nueva Orán',
    'Tartagal',
    'Rosario de la Frontera',
    'Cafayate',
  ],
  'Entre Ríos': [
    'Paraná',
    'Concordia',
    'Gualeguaychú',
    'Concepción del Uruguay',
    'Colón',
  ],
  'Corrientes': [
    'Corrientes',
    'Goya',
    'Paso de los Libres',
    'Mercedes',
    'Curuzú Cuatiá',
  ],
  'Misiones': [
    'Posadas',
    'Oberá',
    'Puerto Iguazú',
    'Eldorado',
    'Apóstoles',
  ],
  'Chaco': [
    'Resistencia',
    'Presidente Roque Sáenz Peña',
    'Villa Ángela',
    'Charata',
  ],
  'Río Negro': [
    'Viedma',
    'Bariloche',
    'Cipolletti',
    'General Roca',
    'Allen',
  ],
  'Neuquén': [
    'Neuquén',
    'San Martín de los Andes',
    'Zapala',
    'Cutral-Có',
    'Junín de los Andes',
  ],
  'Jujuy': [
    'San Salvador de Jujuy',
    'Palpalá',
    'Libertador General San Martín',
    'Humahuaca',
  ],
  'San Juan': [
    'San Juan',
    'Rawson',
    'Chimbas',
    'Caucete',
    'Rivadavia',
  ],
  'La Pampa': [
    'Santa Rosa',
    'General Pico',
    'Toay',
    'Eduardo Castex',
  ],
  'Santiago del Estero': [
    'Santiago del Estero',
    'La Banda',
    'Termas de Río Hondo',
    'Añatuya',
  ],
  'Catamarca': [
    'San Fernando del Valle de Catamarca',
    'San Isidro',
    'Recreo',
    'Tinogasta',
  ],
  'La Rioja': [
    'La Rioja',
    'Chilecito',
    'Chamical',
  ],
  'San Luis': [
    'San Luis',
    'Villa Mercedes',
    'Merlo',
    'Justo Daract',
  ],
};
