/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/leagues/{leagueId}/matches/{matchId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchLeagueMatchResult"];
        trace?: never;
    };
    "/challenges/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getChallengesInbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyPlayerProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMyPlayerProfile"];
        trace?: never;
    };
    "/competitive/profile/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompetitiveProfileHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LeagueMatchSet: {
            a: number;
            b: number;
        };
        LeagueMatchScore: {
            sets: components["schemas"]["LeagueMatchSet"][];
        };
        LeagueMatchResultPatchRequest: {
            /** Format: date-time */
            playedAt: string;
            score: components["schemas"]["LeagueMatchScore"];
        };
        UserBasic: {
            userId: string;
            email: string;
            displayName: string;
        } & {
            [key: string]: unknown;
        };
        ChallengeTeamA: {
            p1: components["schemas"]["UserBasic"];
            p2: components["schemas"]["UserBasic"] | null;
        } & {
            [key: string]: unknown;
        };
        ChallengeTeamB: {
            p1: components["schemas"]["UserBasic"] | null;
            p2: components["schemas"]["UserBasic"] | null;
        } & {
            [key: string]: unknown;
        };
        Challenge: {
            id: string;
            /** @enum {string} */
            type: "direct" | "open";
            /** @enum {string} */
            status: "pending" | "accepted" | "ready" | "rejected" | "cancelled";
            targetCategory: number | null;
            reservationId: string | null;
            message: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            teamA: components["schemas"]["ChallengeTeamA"];
            teamB: components["schemas"]["ChallengeTeamB"];
            invitedOpponent: components["schemas"]["UserBasic"] | null;
            isReady: boolean;
        } & {
            [key: string]: unknown;
        };
        PlayerProfileLookingFor: {
            rival: boolean;
            partner: boolean;
        };
        PlayerProfileLocation: {
            city: string | null;
            province: string | null;
            country: string | null;
        };
        PlayerProfile: {
            playStyleTags: string[];
            bio: string | null;
            lookingFor: components["schemas"]["PlayerProfileLookingFor"];
            location: components["schemas"]["PlayerProfileLocation"];
            /** Format: date-time */
            updatedAt?: string | null;
        } & {
            [key: string]: unknown;
        };
        UpdatePlayerProfileRequest: {
            playStyleTags: string[];
            bio: string | null;
            lookingFor: components["schemas"]["PlayerProfileLookingFor"];
            location: components["schemas"]["PlayerProfileLocation"];
        };
        EloHistoryPoint: {
            id: string;
            eloBefore: number;
            eloAfter: number;
            delta: number;
            reason: string;
            refId: string | null;
            /** Format: date-time */
            createdAt: string;
        } & {
            [key: string]: unknown;
        };
        EloHistoryResponse: {
            items: components["schemas"]["EloHistoryPoint"][];
            nextCursor: string | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    patchLeagueMatchResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
                matchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeagueMatchResultPatchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getChallengesInbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inbox challenge list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Challenge"][];
                };
            };
        };
    };
    getMyPlayerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description My player profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerProfile"];
                };
            };
        };
    };
    updateMyPlayerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlayerProfileRequest"];
            };
        };
        responses: {
            /** @description Updated player profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerProfile"];
                };
            };
        };
    };
    getCompetitiveProfileHistory: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ELO history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EloHistoryResponse"];
                };
            };
        };
    };
}
